ACCOUNTS=["GA7URRUCNFMZ6SQLOLHXB26AJ43JM72Q63NC35SB2STTDHNK6EPH73LW"]

[DOCUMENTATION]
ORG_NAME="PHX"
ORG_URL="https://minephx.cloud"
ORG_LOGO="https://minephx.cloud/logo.svg"
ORG_DESCRIPTION="Phoenix X Currency is a fully decentralized currency, designed for easy and accessible mining by anyone."

[[CURRENCIES]]
code="PHX"
issuer="GA7URRUCNFMZ6SQLOLHXB26AJ43JM72Q63NC35SB2STTDHNK6EPH73LW"
display_decimals=4
name="Phoenix X Currency"
desc="Phoenix X Currency is a fully decentralized currency, designed for easy and accessible mining by anyone."
image="https://minephx.cloud/logo.svg"
