# stellar.toml for minephx.cloud

HOME_DOMAIN="minephx.cloud"
ACCOUNTS=["GA7URRUCNFMZ6SQLOLHXB26AJ43JM72Q63NC35SB2STTDHNK6EPH73LW"]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="PHX"
ORG_URL="https://minephx.cloud"
ORG_LOGO="https://minephx.cloud/Logo.png"
ORG_DESCRIPTION="PHX is a mobile mining application asset."

[[CURRENCIES]]
code="PHX"
issuer="GA7URRUCNFMZ6SQLOLHXB26AJ43JM72Q63NC35SB2STTDHNK6EPH73LW"
name="Phoenix"
desc="PHX is the native asset for the PHX mobile mining application, rewarding users for their participation and engagement."
image="https://minephx.cloud/Logo.png"