# stellar.toml for PHX

ACCOUNTS=["GA7URRUCNFMZ6SQLOLHXB26AJ43JM72Q63NC35SB2STTDHNK6EPH73LW"]
DOCUMENTATION="https://github.com/signlee789/phx"

[[CURRENCIES]]
code="PHX"
issuer="GA7URRUCNFMZ6SQLOLHXB26AJ43JM72Q63NC35SB2STTDHNK6EPH73LW"
name="PHX"
desc="PHX is a decentralized digital currency designed for fair participation through a Proof of Daily Engagement model. It allows web-based mining without special hardware, focusing on accessibility and sustainable community growth."
image="https://phxlast-34481.web.app/logo.svg"
